# Generated by Django 5.1.5 on 2025-02-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='temp_pass123', max_length=255),
            preserve_default=False,
        ),
    ]
