# Generated by Django 5.1.4 on 2025-02-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='argon2$argon2id$v=19$m=102400,t=2,p=8$dDVIUzFhaUFsT3plbGRJNTEzS1pKYw$SHQ9AEsHx0i/nFam+uMnJHSf0iLygAaCTGPIIDkNjwU', max_length=128),
        ),
    ]
